# Generated by Django 4.2.10 on 2024-02-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ticketnumber', models.TextField()),
                ('user', models.TextField()),
                ('date', models.TextField()),
                ('description', models.TextField()),
                ('solution', models.TextField()),
                ('state', models.BooleanField(default=False)),
            ],
        ),
    ]
