# Generated by Django 4.2.10 on 2024-02-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0002_alter_tickets_solution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='state',
        ),
        migrations.AddField(
            model_name='tickets',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
    ]
