# Generated by Django 4.2.10 on 2024-02-25 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0004_users'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='mail',
            new_name='email',
        ),
    ]
