# Generated by Django 4.2.10 on 2024-02-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0005_rename_mail_users_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='secret',
            field=models.TextField(default=''),
        ),
    ]
