# Generated by Django 4.2.10 on 2024-02-26 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0006_users_secret'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='ticketnumber',
        ),
    ]
