# Generated by Django 4.2.10 on 2024-02-28 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_remove_tickets_ticketnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='user_email',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
    ]
