# Generated by Django 4.2.10 on 2024-02-29 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_alter_users_email_alter_users_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='user_email',
        ),
        migrations.AddField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.users'),
        ),
    ]
