# Generated by Django 4.2.10 on 2024-02-29 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0011_remove_tickets_user_email_tickets_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.AddField(
            model_name='tickets',
            name='user_email',
            field=models.TextField(default=''),
        ),
    ]
