# Generated by Django 4.2.10 on 2024-02-29 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0014_alter_tickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='helpdesk.users'),
        ),
    ]
