# Generated by Django 4.2.10 on 2024-02-29 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0017_alter_tickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='tickets',
            name='solution',
            field=models.TextField(blank=True),
        ),
    ]
