# Generated by Django 4.2.10 on 2024-02-29 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0018_alter_tickets_date_alter_tickets_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
