# Generated by Django 4.2.10 on 2024-02-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_alter_tickets_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='date',
            field=models.DateField(blank=True),
        ),
    ]
