# Generated by Django 4.2.10 on 2024-03-01 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0023_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tickets',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='helpdesk.users'),
        ),
    ]
